//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace foodAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<catTOsub> catTOsub { get; set; }
        public virtual DbSet<detail> detail { get; set; }
        public virtual DbSet<detailSubjoin> detailSubjoin { get; set; }
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<menuSubjoinList> menuSubjoinList { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<subCategory> subCategory { get; set; }
        public virtual DbSet<subjoin> subjoin { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
